# Generated by Django 5.1.14 on 2026-01-09 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orchestrator', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='run',
            name='approval_status',
            field=models.CharField(choices=[('none', 'No Approval Required'), ('pending', 'Pending Approval'), ('approved', 'Approved'), ('denied', 'Denied')], default='none', max_length=20),
        ),
        migrations.AddField(
            model_name='run',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='run',
            name='approved_by',
            field=models.CharField(blank=True, help_text='Username or identifier of approver', max_length=255),
        ),
    ]
