# Generated by Django 5.1.14 on 2026-01-09 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orchestrator', '0002_run_approval_status_run_approved_at_run_approved_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='run',
            name='use_rag',
            field=models.BooleanField(default=False, help_text='If True, perform RAG retrieval before LLM calls in this run'),
        ),
    ]
