# Generated by Django 5.1.14 on 2026-01-09 01:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_workerhost_containerinventory_worker_host'),
        ('orchestrator', '0003_run_use_rag'),
    ]

    operations = [
        migrations.AddField(
            model_name='run',
            name='worker_host',
            field=models.ForeignKey(blank=True, help_text='Worker host assigned to execute this run', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='runs', to='core.workerhost'),
        ),
        migrations.AlterField(
            model_name='job',
            name='task_type',
            field=models.CharField(choices=[('log_triage', 'Log Triage'), ('gpu_report', 'GPU Report'), ('service_map', 'Service Map'), ('repo_copilot_plan', 'Repo Co-Pilot Plan')], max_length=50),
        ),
    ]
