# Generated by Django 5.1.14 on 2026-01-08 17:53

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContainerAllowlist',
            fields=[
                ('container_id', models.CharField(help_text='Docker container ID (full or short form)', max_length=255, primary_key=True, serialize=False)),
                ('container_name', models.CharField(help_text='Container name metadata', max_length=255)),
                ('description', models.TextField(blank=True)),
                ('enabled', models.BooleanField(default=True)),
                ('tags', models.JSONField(default=list, help_text='Tags for organizing containers')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['container_name'],
                'indexes': [models.Index(fields=['enabled', 'container_name'], name='core_contai_enabled_470a86_idx'), models.Index(fields=['-created_at'], name='core_contai_created_d64d9a_idx')],
            },
        ),
        migrations.CreateModel(
            name='Directive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('directive_type', models.CharField(choices=[('D1', 'Log Triage (D1)'), ('D2', 'GPU Report (D2)'), ('D3', 'Service Map (D3)'), ('D4', 'Custom Directive (D4)')], max_length=2)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True)),
                ('task_config', models.JSONField(default=dict, help_text='Configuration parameters for tasks')),
                ('directive_text', models.TextField(blank=True, help_text='Directive text/body (optional)')),
                ('is_builtin', models.BooleanField(default=False, help_text='True when this directive is part of the default D1-D4 library')),
                ('version', models.IntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['directive_type', 'name'],
                'indexes': [models.Index(fields=['directive_type', 'is_active'], name='core_direct_directi_0b009d_idx'), models.Index(fields=['created_at'], name='core_direct_created_a55735_idx')],
            },
        ),
        migrations.CreateModel(
            name='GPUState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gpu_id', models.CharField(help_text="GPU device identifier (e.g., '0', '1')", max_length=50, unique=True)),
                ('gpu_name', models.CharField(help_text="GPU model name (e.g., 'NVIDIA GeForce RTX 4090')", max_length=255)),
                ('total_vram_mb', models.IntegerField(help_text='Total VRAM in MB')),
                ('used_vram_mb', models.IntegerField(help_text='Currently used VRAM in MB')),
                ('free_vram_mb', models.IntegerField(help_text='Available VRAM in MB')),
                ('utilization_percent', models.FloatField(default=0.0, help_text='GPU utilization percentage (0-100)')),
                ('is_available', models.BooleanField(default=True)),
                ('active_workers', models.IntegerField(default=0, help_text='Number of workers currently using this GPU')),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['gpu_id'],
                'indexes': [models.Index(fields=['is_available', 'utilization_percent'], name='core_gpusta_is_avai_b273cb_idx'), models.Index(fields=['-last_updated'], name='core_gpusta_last_up_04b8b1_idx')],
            },
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_key', models.CharField(choices=[('log_triage', 'Log Triage'), ('gpu_report', 'GPU Report'), ('service_map', 'Service Map')], max_length=50)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('default_directive', models.CharField(blank=True, choices=[('D1', 'D1'), ('D2', 'D2'), ('D3', 'D3')], help_text='Default directive to apply for this task (D1/D2/D3)', max_length=2)),
                ('config', models.JSONField(default=dict, help_text='Default configuration for this task')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['task_key', 'name'],
                'indexes': [models.Index(fields=['task_key', 'is_active'], name='core_job_task_ke_ba4019_idx'), models.Index(fields=['default_directive', 'is_active'], name='core_job_default_ba6c15_idx')],
            },
        ),
        migrations.CreateModel(
            name='Run',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('directive_snapshot', models.JSONField(default=dict, help_text="Directive snapshot (e.g., {'name': 'D1', 'text': '...'}). NO LLM content.")),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('success', 'Success'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('report_markdown', models.TextField(blank=True, help_text='GUARDRAIL: Markdown summary only, NO LLM prompts/responses')),
                ('report_json', models.JSONField(default=dict, help_text='GUARDRAIL: Structured results only, NO LLM prompts/responses')),
                ('report_markdown_path', models.CharField(blank=True, help_text='Relative path to markdown report under CYBER_BRAIN_LOGS', max_length=512)),
                ('report_json_path', models.CharField(blank=True, help_text='Relative path to JSON report under CYBER_BRAIN_LOGS', max_length=512)),
                ('output_path', models.CharField(blank=True, help_text='Base output path/reference for this run under CYBER_BRAIN_LOGS', max_length=512)),
                ('error_message', models.TextField(blank=True)),
                ('total_prompt_tokens', models.IntegerField(default=0)),
                ('total_completion_tokens', models.IntegerField(default=0)),
                ('total_tokens', models.IntegerField(default=0)),
                ('job', models.ForeignKey(help_text='Job template for this run', on_delete=django.db.models.deletion.PROTECT, related_name='runs', to='core.job')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='LLMCall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('worker_id', models.CharField(blank=True, help_text='Worker/container identifier', max_length=255)),
                ('endpoint', models.CharField(choices=[('vllm', 'vLLM'), ('llama_cpp', 'llama.cpp')], help_text='LLM endpoint type', max_length=50)),
                ('model_id', models.CharField(help_text="Model identifier (e.g., 'llama2', 'mistral')", max_length=255)),
                ('prompt_tokens', models.IntegerField(default=0)),
                ('completion_tokens', models.IntegerField(default=0)),
                ('total_tokens', models.IntegerField(default=0)),
                ('duration_ms', models.IntegerField(blank=True, help_text='Duration of API call in milliseconds', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='llm_calls', to='core.run')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ContainerInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('container_id', models.CharField(db_index=True, max_length=255)),
                ('container_name', models.CharField(db_index=True, max_length=255)),
                ('snapshot_data', models.JSONField(help_text='Complete container state snapshot (status, image, networks, etc.)')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('run', models.ForeignKey(blank=True, help_text='Optional: Run that triggered this snapshot', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='container_snapshots', to='core.run')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RunArtifact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artifact_type', models.CharField(choices=[('markdown', 'Markdown Report'), ('json', 'JSON Report'), ('log', 'Log File'), ('data', 'Data File'), ('other', 'Other')], max_length=20)),
                ('path', models.CharField(help_text='Relative path under CYBER_BRAIN_LOGS', max_length=512)),
                ('file_size_bytes', models.BigIntegerField(default=0)),
                ('mime_type', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artifacts', to='core.run')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RunJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('success', 'Success'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('result', models.JSONField(default=dict, help_text='GUARDRAIL: Structured results only, NO LLM prompts/responses')),
                ('error_message', models.TextField(blank=True)),
                ('prompt_tokens', models.IntegerField(default=0)),
                ('completion_tokens', models.IntegerField(default=0)),
                ('total_tokens', models.IntegerField(default=0)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executions', to='core.job')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='run_jobs', to='core.run')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='WorkerAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation', models.CharField(choices=[('spawn', 'Worker Spawned'), ('start', 'Worker Started'), ('stop', 'Worker Stopped'), ('remove', 'Worker Removed'), ('error', 'Worker Error')], max_length=20)),
                ('container_id', models.CharField(blank=True, max_length=255)),
                ('image_name', models.CharField(max_length=255)),
                ('gpu_assigned', models.CharField(blank=True, help_text="GPU device ID assigned (e.g., '0', '1', 'none' for CPU)", max_length=50)),
                ('gpu_selection_reason', models.TextField(blank=True, help_text='Why this GPU was selected (VRAM headroom, utilization, etc.)')),
                ('config_snapshot', models.JSONField(default=dict, help_text='Worker configuration at operation time')),
                ('success', models.BooleanField(default=True)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('run_job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='worker_audits', to='core.runjob')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkerImageAllowlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_name', models.CharField(help_text="Docker image name (e.g., 'cyberbrain/worker:latest')", max_length=255, unique=True)),
                ('image_tag', models.CharField(default='latest', help_text='Image tag/version', max_length=100)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('requires_gpu', models.BooleanField(default=False)),
                ('min_vram_mb', models.IntegerField(default=0, help_text='Minimum VRAM required in MB (0 = no requirement)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['image_name'],
                'indexes': [models.Index(fields=['is_active', 'requires_gpu'], name='core_worker_is_acti_fb51e8_idx')],
                'unique_together': {('image_name', 'image_tag')},
            },
        ),
        migrations.AddIndex(
            model_name='run',
            index=models.Index(fields=['status', '-started_at'], name='core_run_status_2b37fd_idx'),
        ),
        migrations.AddIndex(
            model_name='run',
            index=models.Index(fields=['-ended_at'], name='core_run_ended_a_609cc9_idx'),
        ),
        migrations.AddIndex(
            model_name='run',
            index=models.Index(fields=['status', '-ended_at'], name='idx_status_ended'),
        ),
        migrations.AddIndex(
            model_name='llmcall',
            index=models.Index(fields=['run', '-created_at'], name='core_llmcal_run_id_6ada14_idx'),
        ),
        migrations.AddIndex(
            model_name='llmcall',
            index=models.Index(fields=['model_id', '-created_at'], name='core_llmcal_model_i_1f289c_idx'),
        ),
        migrations.AddIndex(
            model_name='llmcall',
            index=models.Index(fields=['endpoint', '-created_at'], name='core_llmcal_endpoin_1529f7_idx'),
        ),
        migrations.AddIndex(
            model_name='llmcall',
            index=models.Index(fields=['run', 'model_id'], name='core_llmcal_run_id_841825_idx'),
        ),
        migrations.AddIndex(
            model_name='llmcall',
            index=models.Index(fields=['run', 'endpoint', '-created_at'], name='core_llmcal_run_id_020e5a_idx'),
        ),
        migrations.AddIndex(
            model_name='containerinventory',
            index=models.Index(fields=['container_id', '-created_at'], name='core_contai_contain_235478_idx'),
        ),
        migrations.AddIndex(
            model_name='containerinventory',
            index=models.Index(fields=['container_name', '-created_at'], name='core_contai_contain_bfb52c_idx'),
        ),
        migrations.AddIndex(
            model_name='containerinventory',
            index=models.Index(fields=['-created_at'], name='core_contai_created_823289_idx'),
        ),
        migrations.AddIndex(
            model_name='runartifact',
            index=models.Index(fields=['run', 'artifact_type'], name='core_runart_run_id_288a1e_idx'),
        ),
        migrations.AddIndex(
            model_name='runartifact',
            index=models.Index(fields=['-created_at'], name='core_runart_created_6a7866_idx'),
        ),
        migrations.AddIndex(
            model_name='runjob',
            index=models.Index(fields=['run', 'status'], name='core_runjob_run_id_184c3c_idx'),
        ),
        migrations.AddIndex(
            model_name='runjob',
            index=models.Index(fields=['job', '-started_at'], name='core_runjob_job_id_2df5ca_idx'),
        ),
        migrations.AddIndex(
            model_name='workeraudit',
            index=models.Index(fields=['run_job', '-created_at'], name='core_worker_run_job_73d872_idx'),
        ),
        migrations.AddIndex(
            model_name='workeraudit',
            index=models.Index(fields=['operation', '-created_at'], name='core_worker_operati_cae9ff_idx'),
        ),
        migrations.AddIndex(
            model_name='workeraudit',
            index=models.Index(fields=['container_id'], name='core_worker_contain_eb1919_idx'),
        ),
    ]
