# Generated by Django 5.1.14 on 2026-01-08 23:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_e2_schema'),
        ('orchestrator', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('custom_directive_text', models.TextField(blank=True)),
                ('enabled', models.BooleanField(default=True)),
                ('schedule_type', models.CharField(choices=[('interval', 'Interval'), ('cron', 'Cron')], max_length=20)),
                ('interval_minutes', models.IntegerField(blank=True, null=True)),
                ('cron_expr', models.CharField(blank=True, max_length=100)),
                ('timezone', models.CharField(default='UTC', max_length=100)),
                ('task3_scope', models.CharField(choices=[('allowlist', 'Allowlist Only'), ('all', 'All Containers')], default='allowlist', max_length=20)),
                ('max_global', models.IntegerField(blank=True, help_text='Max concurrent runs across all jobs', null=True)),
                ('max_per_job', models.IntegerField(blank=True, help_text='Max concurrent runs for this job type', null=True)),
                ('last_run_at', models.DateTimeField(blank=True, null=True)),
                ('next_run_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ScheduledRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('started', 'Started'), ('finished', 'Finished'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('error_summary', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.RenameIndex(
            model_name='job',
            new_name='core_job_default_1e309b_idx',
            old_name='core_job_default_ba6c15_idx',
        ),
        migrations.AddField(
            model_name='schedule',
            name='directive',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='schedules', to='core.directive'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='schedules', to='core.job'),
        ),
        migrations.AddField(
            model_name='scheduledrun',
            name='run',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='scheduled_entries', to='orchestrator.run'),
        ),
        migrations.AddField(
            model_name='scheduledrun',
            name='schedule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='core.schedule'),
        ),
        migrations.AddIndex(
            model_name='schedule',
            index=models.Index(fields=['enabled', 'next_run_at'], name='core_schedu_enabled_4e18a6_idx'),
        ),
        migrations.AddIndex(
            model_name='schedule',
            index=models.Index(fields=['schedule_type'], name='core_schedu_schedul_228941_idx'),
        ),
        migrations.AddIndex(
            model_name='scheduledrun',
            index=models.Index(fields=['schedule', '-created_at'], name='core_schedu_schedul_0e6b6d_idx'),
        ),
        migrations.AddIndex(
            model_name='scheduledrun',
            index=models.Index(fields=['run'], name='core_schedu_run_id_eec469_idx'),
        ),
    ]
