# Generated by Django 5.1.14 on 2026-01-09 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_schedule_scheduledrun_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='claimed_by',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='schedule',
            name='claimed_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='schedule',
            index=models.Index(fields=['claimed_until'], name='core_schedu_claimed_64edbe_idx'),
        ),
    ]
