# Generated by Django 5.1.14 on 2026-01-09 00:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_schedule_claimed_by_schedule_claimed_until_and_more'),
        ('orchestrator', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('source', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Chunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chunk_index', models.IntegerField()),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='core.document')),
            ],
            options={
                'ordering': ['document', 'chunk_index'],
            },
        ),
        migrations.CreateModel(
            name='Embedding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('embedding_model_id', models.CharField(max_length=100)),
                ('vector', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('chunk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='embeddings', to='core.chunk')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RetrievalEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query_hash', models.CharField(db_index=True, max_length=64)),
                ('top_k', models.IntegerField()),
                ('results_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='retrieval_events', to='orchestrator.run')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UploadFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=255)),
                ('mime_type', models.CharField(max_length=100)),
                ('size_bytes', models.BigIntegerField()),
                ('sha256', models.CharField(db_index=True, max_length=64, unique=True)),
                ('stored_path', models.CharField(max_length=512)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('processing', 'Processing'), ('ready', 'Ready'), ('failed', 'Failed')], default='queued', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-uploaded_at'],
                'indexes': [models.Index(fields=['status', '-uploaded_at'], name='core_upload_status_621e82_idx'), models.Index(fields=['sha256'], name='core_upload_sha256_d6e5ca_idx')],
            },
        ),
        migrations.AddField(
            model_name='document',
            name='upload',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='core.uploadfile'),
        ),
        migrations.AddIndex(
            model_name='chunk',
            index=models.Index(fields=['document', 'chunk_index'], name='core_chunk_documen_1036af_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='chunk',
            unique_together={('document', 'chunk_index')},
        ),
        migrations.AddIndex(
            model_name='embedding',
            index=models.Index(fields=['chunk'], name='core_embedd_chunk_i_ced3cc_idx'),
        ),
        migrations.AddIndex(
            model_name='embedding',
            index=models.Index(fields=['embedding_model_id'], name='core_embedd_embeddi_b75132_idx'),
        ),
        migrations.AddIndex(
            model_name='retrievalevent',
            index=models.Index(fields=['run', '-created_at'], name='core_retrie_run_id_254a49_idx'),
        ),
        migrations.AddIndex(
            model_name='retrievalevent',
            index=models.Index(fields=['query_hash'], name='core_retrie_query_h_8741cd_idx'),
        ),
        migrations.AddIndex(
            model_name='retrievalevent',
            index=models.Index(fields=['-created_at'], name='core_retrie_created_e9a99d_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['upload', '-created_at'], name='core_docume_upload__6bf21d_idx'),
        ),
    ]
