# Generated by Django 5.1.14 on 2026-01-09 00:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_document_chunk_embedding_retrievalevent_uploadfile_and_more'),
        ('orchestrator', '0002_run_approval_status_run_approved_at_run_approved_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('discord', 'Discord Webhook'), ('email', 'Email')], max_length=20)),
                ('enabled', models.BooleanField(default=True)),
                ('config', models.JSONField(help_text='Configuration: {"webhook_url": "..."} or {"email": "..."}')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['enabled', 'type'], name='core_notifi_enabled_d52a7a_idx')],
            },
        ),
        migrations.CreateModel(
            name='NetworkPolicyRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_service', models.CharField(max_length=255)),
                ('target_service', models.CharField(max_length=255)),
                ('port', models.IntegerField(blank=True, null=True)),
                ('protocol', models.CharField(default='tcp', max_length=20)),
                ('recommendation', models.TextField(help_text='Human-readable policy recommendation')),
                ('policy_yaml', models.TextField(blank=True, help_text='Generated K8s NetworkPolicy YAML')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='network_policies', to='orchestrator.run')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['run', '-created_at'], name='core_networ_run_id_5cb8c2_idx'), models.Index(fields=['source_service', 'target_service'], name='core_networ_source__25cc82_idx')],
            },
        ),
        migrations.CreateModel(
            name='RunNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('error_summary', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='orchestrator.run')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='core.notificationtarget')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['run', '-created_at'], name='core_runnot_run_id_b4a602_idx'), models.Index(fields=['target', 'status'], name='core_runnot_target__6e9038_idx'), models.Index(fields=['status', '-created_at'], name='core_runnot_status_129b7f_idx')],
            },
        ),
    ]
