# Generated by Django 5.1.14 on 2026-01-09 01:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_enable_pgvector'),
    ]

    operations = [
        migrations.AddField(
            model_name='directive',
            name='approval_required',
            field=models.BooleanField(default=False, help_text='Require human approval before execution'),
        ),
        migrations.AddField(
            model_name='directive',
            name='max_concurrent_runs',
            field=models.IntegerField(default=5, help_text='Max concurrent task runs'),
        ),
        migrations.AddField(
            model_name='directive',
            name='task_list',
            field=models.JSONField(default=list, help_text='List of allowed task IDs (log_triage, gpu_report, service_map)'),
        ),
        migrations.CreateModel(
            name='AgentRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operator_goal', models.TextField(help_text='Human-written goal/prompt for the agent')),
                ('directive_snapshot', models.JSONField(default=dict, help_text='Directive configuration at agent creation time (no prompts/responses)')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('pending_approval', 'Pending Approval'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('timeout', 'Timeout'), ('expired', 'Expired (Budget)')], default='pending', max_length=30)),
                ('current_step', models.IntegerField(default=0, help_text='Index of currently executing step')),
                ('max_steps', models.IntegerField(default=10)),
                ('time_budget_minutes', models.IntegerField(default=60)),
                ('token_budget', models.IntegerField(default=10000)),
                ('tokens_used', models.IntegerField(default=0)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('report_markdown', models.TextField(blank=True, help_text='Final markdown report')),
                ('report_json', models.JSONField(default=dict, help_text='Structured results (no prompts/responses)')),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', '-created_at'], name='core_agentr_status_b28721_idx'), models.Index(fields=['-ended_at'], name='core_agentr_ended_a_bceb23_idx'), models.Index(fields=['status', 'current_step'], name='core_agentr_status_a0d4eb_idx')],
            },
        ),
        migrations.CreateModel(
            name='AgentStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_index', models.IntegerField()),
                ('step_type', models.CharField(choices=[('task_call', 'Task Call'), ('decision', 'Decision'), ('wait', 'Wait'), ('notify', 'Notify')], max_length=20)),
                ('task_id', models.CharField(blank=True, help_text='Task ID for task_call steps (log_triage, gpu_report, service_map)', max_length=100)),
                ('inputs', models.JSONField(default=dict, help_text='Step inputs/parameters (no LLM content)')),
                ('outputs_ref', models.CharField(blank=True, help_text='Path/reference to step outputs under CYBER_BRAIN_LOGS', max_length=512)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('success', 'Success'), ('failed', 'Failed'), ('skipped', 'Skipped')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('task_run_id', models.IntegerField(blank=True, help_text='ID of launched Run for task_call steps', null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agent_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='core.agentrun')),
            ],
            options={
                'ordering': ['agent_run', 'step_index'],
                'indexes': [models.Index(fields=['agent_run', 'step_index'], name='core_agents_agent_r_81955f_idx'), models.Index(fields=['agent_run', 'status'], name='core_agents_agent_r_4d3e83_idx'), models.Index(fields=['status', '-created_at'], name='core_agents_status_91caa1_idx')],
                'unique_together': {('agent_run', 'step_index')},
            },
        ),
    ]
