# Generated by Django 5.1.14 on 2026-01-09 01:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_directive_approval_required_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RepoCopilotPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repo_url', models.URLField(max_length=500)),
                ('base_branch', models.CharField(max_length=255)),
                ('goal', models.TextField()),
                ('directive_snapshot', models.JSONField(default=dict, help_text='Snapshot of directive at plan generation time')),
                ('plan', models.JSONField(default=dict, help_text='Plan structure: files, edits, commands, checks, risk_notes, markdown')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('generating', 'Generating Plan'), ('success', 'Plan Generated'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('tokens_used', models.IntegerField(default=0)),
                ('directive', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='repo_copilot_plans', to='core.directive')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', '-created_at'], name='core_repoco_status_4dff16_idx'), models.Index(fields=['-created_at'], name='core_repoco_created_ffde91_idx'), models.Index(fields=['repo_url', '-created_at'], name='core_repoco_repo_ur_920848_idx')],
            },
        ),
    ]
