# Generated by Django 5.1.14 on 2026-01-09 01:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_repocopilotplan'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkerHost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('type', models.CharField(choices=[('docker_socket', 'Docker Socket (Local)'), ('docker_tcp', 'Docker TCP (Remote)')], max_length=20)),
                ('base_url', models.CharField(help_text='Docker connection URL (unix:///path or tcp://host:port)', max_length=500)),
                ('capabilities', models.JSONField(default=dict, help_text='Host capabilities: gpus, gpu_count, labels, max_concurrency')),
                ('ssh_config', models.JSONField(default=dict, help_text='SSH connection info: host, port, user, key_path (secrets, not logged)')),
                ('enabled', models.BooleanField(default=True, help_text='Host available for task execution')),
                ('healthy', models.BooleanField(default=True, help_text='Health check status')),
                ('active_runs_count', models.IntegerField(default=0, help_text='Number of active runs on this host')),
                ('last_seen_at', models.DateTimeField(blank=True, help_text='Last successful health check', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['enabled', 'healthy'], name='core_worker_enabled_2b1498_idx'), models.Index(fields=['-last_seen_at'], name='core_worker_last_se_78d68c_idx'), models.Index(fields=['type'], name='core_worker_type_786831_idx')],
            },
        ),
        migrations.AddField(
            model_name='containerinventory',
            name='worker_host',
            field=models.ForeignKey(blank=True, help_text='Host where this container was observed', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='container_inventories', to='core.workerhost'),
        ),
    ]
